pdf:
	latex Pflichtenheft.tex
	latex Pflichtenheft.tex
	dvips Pflichtenheft
	ps2pdf Pflichtenheft.ps Pflichtenheft.pdf
	mv ./Pflichtenheft.pdf ../

clean:
	rm -rf *.aux
	rm -rf *.log
	rm -rf *.nav
	rm -rf *.toc
	rm -rf *.snm
	rm -rf *.pyg
	rm -rf *.out
	rm -rf *.vrb
	rm -rf *.ps
	rm -rf *.dvi
